const CMS_IMPORT_TYPE_DEFINITIONS = [
  { id: 'nppes_registry', label: 'NPPES Registry', supportsUrl: true },
  { id: 'cms_order_referring', label: 'Order & Referring', supportsUrl: true, availableYears: [2023, 2022, 2021, 2020, 2019] },
  { id: 'provider_service_utilization', label: 'Provider Service Util', supportsUrl: true, availableYears: [2022, 2021, 2020, 2019] },
  { id: 'hospice_enrollments', label: 'Hospice Enrollments', supportsUrl: true, availableYears: [2024, 2023, 2022] },
  { id: 'home_health_enrollments', label: 'Home Health Enrollments', supportsUrl: true, availableYears: [2024, 2023, 2022] },
  { id: 'medicare_hha_stats', label: 'Medicare HHA Stats', supportsUrl: true, availableYears: [2023, 2022, 2021, 2020] },
  { id: 'medicare_ma_inpatient', label: 'Medicare MA Inpatient', supportsUrl: true, availableYears: [2023, 2022, 2021, 2020] },
  { id: 'medicare_snf_stats', label: 'Medicare SNF Stats', supportsUrl: true, availableYears: [2023, 2022, 2021, 2020] },
  { id: 'medical_equipment_suppliers', label: 'Medical Equipment Suppliers', supportsUrl: true, availableYears: [2024, 2023, 2022] },
  { id: 'hospice_provider_measures', label: 'Hospice Provider Measures', supportsUrl: true, availableYears: [2023, 2022, 2021] },
  { id: 'hospice_state_measures', label: 'Hospice State Measures', supportsUrl: true, availableYears: [2023, 2022, 2021] },
  { id: 'hospice_national_measures', label: 'Hospice National Measures', supportsUrl: true, availableYears: [2023, 2022, 2021] },
  { id: 'snf_provider_measures', label: 'SNF Provider Measures', supportsUrl: true, availableYears: [2023, 2022, 2021] },
  { id: 'nursing_home_providers', label: 'Nursing Home Providers', supportsUrl: true, availableYears: [2024, 2023, 2022] },
  { id: 'nursing_home_deficiencies', label: 'Nursing Home Deficiencies', supportsUrl: true, availableYears: [2024, 2023, 2022] },
  { id: 'home_health_national_measures', label: 'Home Health National Measures', supportsUrl: true, availableYears: [2023, 2022, 2021] },
  { id: 'clinician_national_file', label: 'Clinician National File', supportsUrl: true },
  { id: 'clinician_mips_performance', label: 'Clinician MIPS Performance', supportsUrl: true },
  { id: 'clinician_mips_measures', label: 'Clinician MIPS Measures', supportsUrl: true },
  { id: 'clinician_group_measures', label: 'Group Practice Measures', supportsUrl: true },
  { id: 'clinician_group_experience', label: 'Group Practice Experience', supportsUrl: true },
  { id: 'hospital_hcahps_survey', label: 'Hospital HCAHPS Survey', supportsUrl: true },
  { id: 'hospital_timely_effective_care', label: 'Timely & Effective Care', supportsUrl: true },
  { id: 'hospital_unplanned_visits', label: 'Unplanned Hospital Visits', supportsUrl: true },
  { id: 'hospital_imaging_efficiency', label: 'Imaging Efficiency', supportsUrl: true },
  { id: 'hospital_spending_per_beneficiary', label: 'Spending Per Beneficiary', supportsUrl: true },
  { id: 'hospital_spending_by_claim', label: 'Spending by Claim', supportsUrl: true },
  { id: 'hospital_hac_reduction', label: 'HAC Reduction Program', supportsUrl: true },
  { id: 'hospital_psychiatric_facility', label: 'Psychiatric Facility QM', supportsUrl: true },
  { id: 'ambulatory_surgical_center', label: 'Ambulatory Surgical Center', supportsUrl: true },
  { id: 'hospital_joint_replacement', label: 'Joint Replacement Model', supportsUrl: true },
  { id: 'home_health_patient_survey', label: 'Home Health HHCAHPS', supportsUrl: true },
  { id: 'home_health_zip_data', label: 'Home Health Zip Data', supportsUrl: true },
  { id: 'hospice_zip_data', label: 'Hospice Zip Data', supportsUrl: true },
  { id: 'nursing_home_ownership', label: 'Nursing Home Ownership', supportsUrl: true },
  { id: 'nursing_home_fire_safety', label: 'Nursing Home Fire Safety', supportsUrl: true },
  { id: 'nursing_home_health_deficiencies', label: 'Nursing Home Health Deficiencies', supportsUrl: true },
  { id: 'nursing_home_mds_quality', label: 'Nursing Home MDS Quality', supportsUrl: true },
  { id: 'nursing_home_claims_quality', label: 'Nursing Home Claims QM', supportsUrl: true },
  { id: 'snf_quality_reporting', label: 'SNF Quality Reporting', supportsUrl: true },
  { id: 'inpatient_rehab_general_info', label: 'IRF General Information', supportsUrl: true },
  { id: 'inpatient_rehab_provider_data', label: 'IRF Provider Data', supportsUrl: true },
  { id: 'long_term_care_general_info', label: 'LTCH General Information', supportsUrl: true },
  { id: 'long_term_care_provider_data', label: 'LTCH Provider Data', supportsUrl: true },
  { id: 'hospital_general_info', label: 'Hospital General Info', supportsUrl: true },
  { id: 'hospital_enrollments', label: 'Hospital Enrollments', supportsUrl: true },
  { id: 'hospital_all_owners', label: 'Hospital Ownership', supportsUrl: true },
  { id: 'hospital_cost_report', label: 'Hospital Cost Report', supportsUrl: true },
  { id: 'hospital_value_based_purchasing', label: 'Value-Based Purchasing', supportsUrl: true },
  { id: 'hospital_price_transparency', label: 'Price Transparency', supportsUrl: true },
  { id: 'hospital_complications', label: 'Hospital Complications', supportsUrl: true },
  { id: 'hospital_infections', label: 'Hospital Infections', supportsUrl: true },
  { id: 'hospital_readmissions', label: 'Hospital Readmissions', supportsUrl: true },
  { id: 'hospital_service_area', label: 'Hospital Service Area', supportsUrl: true },
  { id: 'home_health_all_owners', label: 'Home Health Ownership', supportsUrl: true },
  { id: 'home_health_state_measures', label: 'Home Health State Measures', supportsUrl: true },
  { id: 'home_health_cost_report', label: 'Home Health Cost Report', supportsUrl: true },
  { id: 'hospice_all_owners', label: 'Hospice Ownership', supportsUrl: true },
  { id: 'hospice_provider_data', label: 'Hospice Provider Data', supportsUrl: true },
  { id: 'nursing_home_penalties', label: 'Nursing Home Penalties', supportsUrl: true },
  { id: 'medical_equipment_suppliers', label: 'DME Suppliers', supportsUrl: true },
  { id: 'medicare_physician_by_provider', label: 'Physician Utilization by Provider', supportsUrl: true },
  { id: 'medicare_part_d_prescribers', label: 'Part D Prescribers', supportsUrl: true },
  { id: 'medicare_dme_by_referring', label: 'DME by Referring Provider', supportsUrl: true },
  { id: 'medicare_dme_by_supplier', label: 'DME by Supplier', supportsUrl: true },
  { id: 'medicare_inpatient_by_provider', label: 'Inpatient by Provider', supportsUrl: true },
  { id: 'medicare_outpatient_by_provider', label: 'Outpatient by Provider', supportsUrl: true },
  { id: 'medicare_fee_for_service_enrollment', label: 'FFS Enrollment', supportsUrl: true },
  { id: 'medicare_monthly_enrollment', label: 'Monthly Enrollment', supportsUrl: true },
  { id: 'medicare_spending_by_drug_b', label: 'Drug Spending Part B', supportsUrl: true },
  { id: 'medicare_spending_by_drug_d', label: 'Drug Spending Part D', supportsUrl: true },
  { id: 'medicare_ma_inpatient', label: 'MA Inpatient', supportsUrl: true },
  { id: 'market_saturation_county', label: 'Market Saturation (County)', supportsUrl: true },
  { id: 'market_saturation_cbsa', label: 'Market Saturation (CBSA)', supportsUrl: true },
  { id: 'provider_taxonomy_crosswalk', label: 'Taxonomy Crosswalk', supportsUrl: true },
  { id: 'facility_affiliation', label: 'Facility Affiliation Data', supportsUrl: true },
  { id: 'home_health_vbp', label: 'Home Health VBP', supportsUrl: true },
  { id: 'snf_vbp_facility', label: 'SNF VBP Facility', supportsUrl: true },
  { id: 'rural_health_clinic_enrollments', label: 'Rural Health Clinic Enrollments', supportsUrl: true },
  { id: 'rural_health_clinic_all_owners', label: 'Rural Health Clinic Ownership', supportsUrl: true },
  { id: 'nursing_home_chain_performance', label: 'NH Chain Performance', supportsUrl: true },
  { id: 'medicare_geographic_variation', label: 'Geographic Variation', supportsUrl: true },
  { id: 'pbj_daily_nurse_staffing', label: 'PBJ Nurse Staffing', supportsUrl: true },
  { id: 'pbj_daily_nonnurse_staffing', label: 'PBJ Non-Nurse Staffing', supportsUrl: true },
  { id: 'snf_enrollments', label: 'SNF Enrollments', supportsUrl: true },
  { id: 'snf_all_owners', label: 'SNF Ownership', supportsUrl: true },
  { id: 'snf_cost_report', label: 'SNF Cost Report', supportsUrl: true },
  { id: 'fqhc_all_owners', label: 'FQHC Ownership', supportsUrl: true },
  { id: 'aco_participants', label: 'ACO Participants', supportsUrl: true },
  { id: 'aco_organizations', label: 'ACO Organizations', supportsUrl: true },
  { id: 'aco_financial_results', label: 'ACO Financial Results', supportsUrl: true },
  { id: 'medicare_telehealth_trends', label: 'Telehealth Trends', supportsUrl: true },
  { id: 'snf_utilization_geo_casemix', label: 'SNF Utilization by Geo/Case-Mix', supportsUrl: true },
  { id: 'hha_utilization_geo_casemix', label: 'HHA Utilization by Geo/Case-Mix', supportsUrl: true },
  { id: 'ltc_facility_characteristics', label: 'LTC Facility Characteristics', supportsUrl: true },
  { id: 'mds_frequency', label: 'MDS Frequency', supportsUrl: true },
];

export const CMS_IMPORT_TYPE_ALIAS_MAP = {
  cms_service_utilization: 'provider_service_utilization',
};

export const CMS_IMPORT_TYPES = CMS_IMPORT_TYPE_DEFINITIONS.map(def => ({
  ...def,
  normalizedId: def.id,
}));

export const CMS_IMPORT_TYPE_LABELS = Object.fromEntries(
  CMS_IMPORT_TYPES.map(({ id, label }) => [id, label]),
);

export const BASE_IMPORT_TYPE_LABELS = {
  nppes_monthly: 'NPPES Monthly',
  nppes_registry: 'NPPES Registry',
  cms_utilization: 'CMS Utilization',
  pa_home_health: 'PA Home Health',
  hospice_providers: 'Hospice Providers',
  nursing_home_chains: 'Nursing Home Chains',
  hospice_enrollments: 'Hospice Enrollments',
  home_health_enrollments: 'Home Health Enrollments',
  home_health_cost_reports: 'Home Health Cost Reports',
  cms_service_utilization: 'Service Utilization',
  provider_service_utilization: 'Provider Service Util',
  home_health_pdgm: 'Home Health PDGM',
  inpatient_drg: 'Inpatient DRG',
  provider_ownership: 'Provider Ownership',
  hospital_hcahps_survey: 'Hospital HCAHPS',
  hospital_timely_effective_care: 'Timely & Effective Care',
  hospital_unplanned_visits: 'Unplanned Visits',
  hospital_imaging_efficiency: 'Imaging Efficiency',
  hospital_spending_per_beneficiary: 'Spending/Beneficiary',
  hospital_spending_by_claim: 'Spending by Claim',
  hospital_hac_reduction: 'HAC Reduction',
  hospital_psychiatric_facility: 'Psychiatric Facility',
  ambulatory_surgical_center: 'ASC Quality',
  hospital_joint_replacement: 'Joint Replacement',
  home_health_patient_survey: 'HHCAHPS Survey',
  home_health_zip_data: 'Home Health Zip',
  hospice_zip_data: 'Hospice Zip',
  nursing_home_ownership: 'NH Ownership',
  nursing_home_fire_safety: 'NH Fire Safety',
  nursing_home_health_deficiencies: 'NH Health Deficiencies',
  nursing_home_mds_quality: 'NH MDS Quality',
  nursing_home_claims_quality: 'NH Claims Quality',
  snf_quality_reporting: 'SNF Quality Reporting',
  inpatient_rehab_general_info: 'IRF General Info',
  inpatient_rehab_provider_data: 'IRF Provider Data',
  long_term_care_general_info: 'LTCH General Info',
  long_term_care_provider_data: 'LTCH Provider Data',
  clinician_national_file: 'Clinician National File',
  clinician_mips_performance: 'Clinician MIPS',
  clinician_mips_measures: 'Clinician MIPS Measures',
  clinician_group_measures: 'Group MIPS Measures',
  clinician_group_experience: 'Group Experience',
  hospital_general_info: 'Hospital General Info',
  hospital_enrollments: 'Hospital Enrollments',
  hospital_all_owners: 'Hospital Ownership',
  hospital_cost_report: 'Hospital Cost Report',
  hospital_value_based_purchasing: 'Value-Based Purchasing',
  hospital_price_transparency: 'Price Transparency',
  hospital_complications: 'Hospital Complications',
  hospital_infections: 'Hospital Infections',
  hospital_readmissions: 'Hospital Readmissions',
  hospital_service_area: 'Hospital Service Area',
  home_health_all_owners: 'Home Health Ownership',
  home_health_state_measures: 'HH State Measures',
  hospice_all_owners: 'Hospice Ownership',
  nursing_home_penalties: 'NH Penalties',
  medicare_physician_by_provider: 'Physician Util by Provider',
  medicare_part_d_prescribers: 'Part D Prescribers',
  medicare_dme_by_referring: 'DME by Referring',
  medicare_dme_by_supplier: 'DME by Supplier',
  medicare_inpatient_by_provider: 'Inpatient by Provider',
  medicare_outpatient_by_provider: 'Outpatient by Provider',
  medicare_fee_for_service_enrollment: 'FFS Enrollment',
  medicare_monthly_enrollment: 'Monthly Enrollment',
  medicare_spending_by_drug_b: 'Drug Spending Part B',
  medicare_spending_by_drug_d: 'Drug Spending Part D',
  market_saturation_county: 'Market Saturation (County)',
  market_saturation_cbsa: 'Market Saturation (CBSA)',
  provider_taxonomy_crosswalk: 'Taxonomy Crosswalk',
  facility_affiliation: 'Facility Affiliation',
  home_health_vbp: 'Home Health VBP',
  snf_vbp_facility: 'SNF VBP Facility',
  rural_health_clinic_enrollments: 'RHC Enrollments',
  rural_health_clinic_all_owners: 'RHC Ownership',
  nursing_home_chain_performance: 'NH Chain Performance',
  medicare_geographic_variation: 'Geographic Variation',
  pbj_daily_nurse_staffing: 'PBJ Nurse Staffing',
  pbj_daily_nonnurse_staffing: 'PBJ Non-Nurse Staffing',
  snf_enrollments: 'SNF Enrollments',
  snf_all_owners: 'SNF Ownership',
  snf_cost_report: 'SNF Cost Report',
  fqhc_all_owners: 'FQHC Ownership',
  aco_participants: 'ACO Participants',
  aco_organizations: 'ACO Organizations',
  aco_financial_results: 'ACO Financial Results',
  medicare_telehealth_trends: 'Telehealth Trends',
  snf_utilization_geo_casemix: 'SNF Util by Geo/Case-Mix',
  hha_utilization_geo_casemix: 'HHA Util by Geo/Case-Mix',
  ltc_facility_characteristics: 'LTC Facility Characteristics',
  mds_frequency: 'MDS Frequency',
  cms_order_referring: 'Order & Referring',
  provider_service_utilization: 'Service Utilization',
  nppes_registry: 'NPPES Registry',
  ...CMS_IMPORT_TYPE_LABELS,
};

export const SCHEDULABLE_CMS_IMPORT_TYPES = CMS_IMPORT_TYPES.filter(type => type.supportsUrl);

export const SCHEDULABLE_CMS_IMPORT_TYPE_IDS = SCHEDULABLE_CMS_IMPORT_TYPES.map(type => type.id);

export const CMS_IMPORT_TYPES_BY_ID = Object.fromEntries(
  CMS_IMPORT_TYPES.map(type => [type.id, type]),
);

export function normalizeCmsImportType(importType) {
  return CMS_IMPORT_TYPE_ALIAS_MAP[importType] || importType;
}

export function getCmsImportTypeLabel(importType) {
  const normalized = normalizeCmsImportType(importType);
  return CMS_IMPORT_TYPE_LABELS[normalized] || normalized;
}

export function getCmsImportTypeYears(importType) {
  const normalized = normalizeCmsImportType(importType);
  return CMS_IMPORT_TYPES_BY_ID[normalized]?.availableYears || null;
}

export function buildImportTypeLabels(overrides = {}) {
  return {
    ...BASE_IMPORT_TYPE_LABELS,
    ...overrides,
  };
}
