import { FileText, Database, TrendingUp, Activity } from 'lucide-react';

export const IMPORT_TYPE_LABELS = {
  'nppes_monthly': 'NPPES Monthly',
  'nppes_registry': 'NPPES Registry',
  'cms_utilization': 'CMS Utilization',
  'cms_part_d': 'CMS Part D',
  'cms_order_referring': 'Order & Referring',
  'pa_home_health': 'PA Home Health',
  'hospice_providers': 'Hospice Providers',
  'nursing_home_chains': 'Nursing Home Chains',
  'hospice_enrollments': 'Hospice Enrollments',
  'home_health_enrollments': 'Home Health Enrollments',
  'home_health_cost_reports': 'Home Health Cost Reports',
  'cms_service_utilization': 'Service Utilization',
  'provider_service_utilization': 'Provider Service Utilization',
  'home_health_pdgm': 'Home Health PDGM',
  'inpatient_drg': 'Inpatient DRG',
  'provider_ownership': 'Provider Ownership',
  'opt_out_physicians': 'Opt-Out Physicians',
  'hospital_general_info': 'Hospital General Info',
  'nursing_home_compare': 'Nursing Home Compare',
  'home_health_compare': 'Home Health Compare',
  'dmepos_suppliers': 'DMEPOS Suppliers',
  'medicare_inpatient_charges': 'Inpatient Charges',
  'medicare_outpatient_charges': 'Outpatient Charges',
  'medicare_hha_stats': 'Medicare HHA Stats',
  'medicare_ma_inpatient': 'Medicare MA Inpatient',
  'medicare_part_d_stats': 'Medicare Part D Stats',
  'medicare_snf_stats': 'Medicare SNF Stats',
};

export const IMPORT_TYPE_SHORT_LABELS = {
  'nppes_monthly': 'NPPES Monthly',
  'nppes_registry': 'NPPES Registry',
  'cms_utilization': 'CMS Util',
  'cms_part_d': 'Part D',
  'cms_order_referring': 'Order/Ref',
  'pa_home_health': 'PA HH',
  'hospice_providers': 'Hospice Prov',
  'nursing_home_chains': 'NH Chains',
  'hospice_enrollments': 'Hospice Enr',
  'home_health_enrollments': 'HH Enr',
  'home_health_cost_reports': 'HH Cost',
  'cms_service_utilization': 'Svc Util',
  'provider_service_utilization': 'Prov Svc',
  'home_health_pdgm': 'HH PDGM',
  'inpatient_drg': 'DRG',
  'provider_ownership': 'Ownership',
  'opt_out_physicians': 'Opt-Out',
  'hospital_general_info': 'Hosp Info',
  'nursing_home_compare': 'NH Compare',
  'home_health_compare': 'HH Compare',
  'dmepos_suppliers': 'DMEPOS',
  'medicare_inpatient_charges': 'Inp Charges',
  'medicare_outpatient_charges': 'Out Charges',
  'medicare_hha_stats': 'HHA Stats',
  'medicare_ma_inpatient': 'MA Inp',
  'medicare_part_d_stats': 'Part D Stats',
  'medicare_snf_stats': 'SNF Stats',
};

export const IMPORT_TYPES = [
  { id: 'nppes_monthly', name: 'NPPES Monthly', desc: 'Provider registry data', icon: FileText, hasUrl: false },
  { id: 'nppes_registry', name: 'NPPES Registry', desc: 'Full NPI registry', icon: FileText, hasUrl: false },
  { id: 'cms_utilization', name: 'CMS Utilization', desc: 'Part B utilization & payment', icon: TrendingUp, hasUrl: false },
  { id: 'cms_part_d', name: 'CMS Part D', desc: 'Prescription drug claims', icon: Activity, hasUrl: true },
  { id: 'cms_order_referring', name: 'Order & Referring', desc: 'Order/referring providers', icon: Database, hasUrl: true },
  { id: 'opt_out_physicians', name: 'Opt-Out Physicians', desc: 'Physicians who opted out of Medicare', icon: Database, hasUrl: true },
  { id: 'provider_service_utilization', name: 'Provider Service Util', desc: 'Provider-level HCPCS', icon: Activity, hasUrl: true },
  { id: 'hospice_enrollments', name: 'Hospice Enrollments', desc: 'CMS hospice enrollment', icon: Database, hasUrl: true },
  { id: 'home_health_enrollments', name: 'HH Enrollments', desc: 'CMS home health enrollment', icon: Database, hasUrl: true },
  { id: 'hospital_general_info', name: 'Hospital General Info', desc: 'Hospital locations, types & ratings', icon: Database, hasUrl: true },
  { id: 'nursing_home_compare', name: 'Nursing Home Compare', desc: 'SNF quality ratings & staffing', icon: TrendingUp, hasUrl: true },
  { id: 'home_health_compare', name: 'Home Health Compare', desc: 'HH quality & patient care ratings', icon: TrendingUp, hasUrl: true },
  { id: 'provider_ownership', name: 'Provider Ownership', desc: 'Ownership/control info', icon: Database, hasUrl: true },
  { id: 'dmepos_suppliers', name: 'DMEPOS Suppliers', desc: 'DME supplier enrollment', icon: Database, hasUrl: true },
  { id: 'medicare_inpatient_charges', name: 'Inpatient Charges', desc: 'Hospital DRG-level charges', icon: TrendingUp, hasUrl: true },
  { id: 'medicare_outpatient_charges', name: 'Outpatient Charges', desc: 'Hospital APC-level charges', icon: TrendingUp, hasUrl: true },
  { id: 'medicare_hha_stats', name: 'Medicare HHA Stats', desc: 'Home health aggregate', icon: Activity, hasUrl: true },
  { id: 'medicare_ma_inpatient', name: 'Medicare MA Inpatient', desc: 'MA inpatient stats', icon: Activity, hasUrl: true },
  { id: 'medicare_part_d_stats', name: 'Medicare Part D Stats', desc: 'Part D aggregate', icon: Activity, hasUrl: true },
  { id: 'medicare_snf_stats', name: 'Medicare SNF Stats', desc: 'SNF aggregate', icon: Activity, hasUrl: true },
];
