import { buildImportTypeLabels } from '@/lib/cmsImportTypes';

const DATA_DESTINATION_MAP = {
  nppes_monthly: { page: 'Providers', label: 'Providers' },
  nppes_registry: { page: 'Providers', label: 'Providers' },

  cms_utilization: { page: 'Utilization', label: 'Utilization' },
  cms_service_utilization: { page: 'Utilization', label: 'Utilization' },
  provider_service_utilization: { page: 'Utilization', label: 'Utilization' },
  cms_order_referring: { page: 'ReferralNetworkIntelligence', label: 'Referrals' },

  hospital_general_info: { page: 'Hospitals', label: 'Hospitals' },
  hospital_enrollments: { page: 'Hospitals', label: 'Hospitals' },
  hospital_all_owners: { page: 'Hospitals', label: 'Hospitals' },
  hospital_cost_report: { page: 'Hospitals', label: 'Hospitals' },
  hospital_readmissions: { page: 'Hospitals', label: 'Hospitals' },
  hospital_hcahps_survey: { page: 'Hospitals', label: 'Hospitals' },
  hospital_timely_effective_care: { page: 'Hospitals', label: 'Hospitals' },
  hospital_spending_per_beneficiary: { page: 'Hospitals', label: 'Hospitals' },
  hospital_spending_by_claim: { page: 'Hospitals', label: 'Hospitals' },
  hospital_hac_reduction: { page: 'Hospitals', label: 'Hospitals' },
  hospital_imaging_efficiency: { page: 'Hospitals', label: 'Hospitals' },
  hospital_service_area: { page: 'Hospitals', label: 'Hospitals' },
  hospital_unplanned_visits: { page: 'Hospitals', label: 'Hospitals' },
  hospital_complications: { page: 'Hospitals', label: 'Hospitals' },
  hospital_infections: { page: 'Hospitals', label: 'Hospitals' },
  hospital_psychiatric_facility: { page: 'Hospitals', label: 'Hospitals' },
  hospital_value_based_purchasing: { page: 'Hospitals', label: 'Hospitals' },
  hospital_price_transparency: { page: 'Hospitals', label: 'Hospitals' },
  hospital_joint_replacement: { page: 'Hospitals', label: 'Hospitals' },
  ambulatory_surgical_center: { page: 'Hospitals', label: 'Hospitals' },
  medicare_inpatient_by_provider: { page: 'Hospitals', label: 'Hospitals' },
  medicare_outpatient_by_provider: { page: 'Hospitals', label: 'Hospitals' },
  medicare_ma_inpatient: { page: 'MAInpatientDashboard', label: 'MA Inpatient' },

  home_health_enrollments: { page: 'HomeHealthAgencies', label: 'Home Health' },
  home_health_all_owners: { page: 'HomeHealthAgencies', label: 'Home Health' },
  home_health_cost_report: { page: 'HomeHealthAgencies', label: 'Home Health' },
  home_health_cost_reports: { page: 'HomeHealthAgencies', label: 'Home Health' },
  home_health_patient_survey: { page: 'HomeHealthAgencies', label: 'Home Health' },
  home_health_national_measures: { page: 'HomeHealthAgencies', label: 'Home Health' },
  home_health_state_measures: { page: 'HomeHealthAgencies', label: 'Home Health' },
  home_health_zip_data: { page: 'HomeHealthAgencies', label: 'Home Health' },
  home_health_vbp: { page: 'HomeHealthAgencies', label: 'Home Health' },
  medicare_hha_stats: { page: 'HomeHealthAgencies', label: 'Home Health' },
  hha_utilization_geo_casemix: { page: 'HomeHealthAgencies', label: 'Home Health' },
  home_health_pdgm: { page: 'HomeHealthAgencies', label: 'Home Health' },
  home_health_agencies: { page: 'HomeHealthAgencies', label: 'Home Health' },
  medicare_hha_utilization: { page: 'HomeHealthAgencies', label: 'Home Health' },
  home_infusion_therapy: { page: 'HomeHealthAgencies', label: 'Home Health' },

  hospice_enrollments: { page: 'Hospices', label: 'Hospices' },
  hospice_all_owners: { page: 'Hospices', label: 'Hospices' },
  hospice_provider_data: { page: 'Hospices', label: 'Hospices' },
  hospice_provider_measures: { page: 'Hospices', label: 'Hospices' },
  hospice_national_measures: { page: 'Hospices', label: 'Hospices' },
  hospice_state_measures: { page: 'Hospices', label: 'Hospices' },
  hospice_zip_data: { page: 'Hospices', label: 'Hospices' },
  hospice_providers: { page: 'Hospices', label: 'Hospices' },
  hospice_general_info: { page: 'Hospices', label: 'Hospices' },
  medicare_hospice_utilization: { page: 'Hospices', label: 'Hospices' },

  snf_provider_measures: { page: 'NursingHomes', label: 'Nursing Homes' },
  snf_quality_reporting: { page: 'NursingHomes', label: 'Nursing Homes' },
  snf_enrollments: { page: 'NursingHomes', label: 'Nursing Homes' },
  snf_all_owners: { page: 'NursingHomes', label: 'Nursing Homes' },
  snf_cost_report: { page: 'NursingHomes', label: 'Nursing Homes' },
  snf_vbp_facility: { page: 'NursingHomes', label: 'Nursing Homes' },
  snf_utilization_geo_casemix: { page: 'NursingHomes', label: 'Nursing Homes' },
  nursing_home_providers: { page: 'NursingHomes', label: 'Nursing Homes' },
  nursing_home_deficiencies: { page: 'NursingHomes', label: 'Nursing Homes' },
  nursing_home_ownership: { page: 'NursingHomes', label: 'Nursing Homes' },
  nursing_home_fire_safety: { page: 'NursingHomes', label: 'Nursing Homes' },
  nursing_home_health_deficiencies: { page: 'NursingHomes', label: 'Nursing Homes' },
  nursing_home_mds_quality: { page: 'NursingHomes', label: 'Nursing Homes' },
  nursing_home_claims_quality: { page: 'NursingHomes', label: 'Nursing Homes' },
  nursing_home_penalties: { page: 'NursingHomes', label: 'Nursing Homes' },
  nursing_home_chains: { page: 'NursingHomes', label: 'Nursing Homes' },
  nursing_home_chain_performance: { page: 'NursingHomes', label: 'Nursing Homes' },
  medicare_snf_stats: { page: 'NursingHomes', label: 'Nursing Homes' },
  medicare_snf_utilization: { page: 'NursingHomes', label: 'Nursing Homes' },
  pbj_daily_nurse_staffing: { page: 'NursingHomes', label: 'Nursing Homes' },
  pbj_daily_nonnurse_staffing: { page: 'NursingHomes', label: 'Nursing Homes' },
  ltc_facility_characteristics: { page: 'NursingHomes', label: 'Nursing Homes' },
  mds_frequency: { page: 'NursingHomes', label: 'Nursing Homes' },

  inpatient_rehab_general_info: { page: 'InpatientRehab', label: 'Inpatient Rehab' },
  inpatient_rehab_provider_data: { page: 'InpatientRehab', label: 'Inpatient Rehab' },
  medicare_irf_utilization: { page: 'InpatientRehab', label: 'Inpatient Rehab' },

  long_term_care_general_info: { page: 'LongTermCare', label: 'Long Term Care' },
  long_term_care_provider_data: { page: 'LongTermCare', label: 'Long Term Care' },
  medicare_ltch_utilization: { page: 'LongTermCare', label: 'Long Term Care' },

  medical_equipment_suppliers: { page: 'DMESuppliers', label: 'DME Suppliers' },
  medicare_dme_by_supplier: { page: 'DMESuppliers', label: 'DME Suppliers' },
  medicare_dme_by_referring: { page: 'DMESuppliers', label: 'DME Suppliers' },

  fqhc_enrollments: { page: 'CommunityHealthCenters', label: 'Community Health' },
  fqhc_all_owners: { page: 'CommunityHealthCenters', label: 'Community Health' },
  rural_health_clinic_enrollments: { page: 'CommunityHealthCenters', label: 'Community Health' },
  rural_health_clinic_all_owners: { page: 'CommunityHealthCenters', label: 'Community Health' },
  aco_snf_affiliates: { page: 'Organizations', label: 'Organizations' },
  aco_reach_providers: { page: 'Organizations', label: 'Organizations' },

  clinician_national_file: { page: 'Providers', label: 'Providers' },
  clinician_mips_performance: { page: 'Providers', label: 'Providers' },
  clinician_mips_measures: { page: 'Providers', label: 'Providers' },
  clinician_group_measures: { page: 'Organizations', label: 'Organizations' },
  clinician_group_experience: { page: 'Organizations', label: 'Organizations' },

  provider_ownership: { page: 'Organizations', label: 'Organizations' },
  facility_affiliation: { page: 'Organizations', label: 'Organizations' },
  aco_participants: { page: 'Organizations', label: 'Organizations' },
  aco_organizations: { page: 'Organizations', label: 'Organizations' },
  aco_financial_results: { page: 'Organizations', label: 'Organizations' },

  medicare_physician_by_provider: { page: 'Utilization', label: 'Utilization' },
  medicare_part_d_prescribers: { page: 'Utilization', label: 'Utilization' },
  inpatient_drg: { page: 'Utilization', label: 'Utilization' },

  medicare_fee_for_service_enrollment: { page: 'CMSAnalytics', label: 'CMS Analytics' },
  medicare_monthly_enrollment: { page: 'CMSAnalytics', label: 'CMS Analytics' },
  medicare_spending_by_drug_b: { page: 'CMSAnalytics', label: 'CMS Analytics' },
  medicare_spending_by_drug_d: { page: 'CMSAnalytics', label: 'CMS Analytics' },
  medicare_geographic_variation: { page: 'CMSAnalytics', label: 'CMS Analytics' },
  medicare_telehealth_trends: { page: 'CMSAnalytics', label: 'CMS Analytics' },
  market_saturation_county: { page: 'CMSAnalytics', label: 'CMS Analytics' },
  market_saturation_cbsa: { page: 'CMSAnalytics', label: 'CMS Analytics' },
  provider_taxonomy_crosswalk: { page: 'CMSAnalytics', label: 'CMS Analytics' },

  pa_home_health: { page: 'HomeHealthAgencies', label: 'Home Health' },
};

const IMPORT_TYPE_LABELS = buildImportTypeLabels({
  home_health_enrollments: 'HH Enrollments',
  home_health_cost_reports: 'HH Cost Reports',
  provider_service_utilization: 'Provider Service Util',
  home_health_pdgm: 'HH PDGM',
});

export { DATA_DESTINATION_MAP, IMPORT_TYPE_LABELS };
