// Central configuration for datasets, their metrics, grouping options, and filters

export const DATASET_CONFIG = {
  cms_utilization: {
    label: 'CMS Provider Utilization',
    entity: 'CMSUtilization',
    metrics: [
      { key: 'total_services', label: 'Total Services' },
      { key: 'total_medicare_beneficiaries', label: 'Medicare Beneficiaries' },
      { key: 'total_submitted_charges', label: 'Submitted Charges ($)' },
      { key: 'total_medicare_allowed', label: 'Medicare Allowed ($)' },
      { key: 'total_medicare_payment', label: 'Medicare Payment ($)' },
      { key: 'drug_services', label: 'Drug Services' },
    ],
    groupOptions: [
      { key: 'year', label: 'Year' },
      { key: 'npi', label: 'Provider NPI' },
    ],
    filters: ['year'],
    yearField: 'year',
  },
  cms_referrals: {
    label: 'CMS Referral Patterns',
    entity: 'CMSReferral',
    metrics: [
      { key: 'total_referrals', label: 'Total Referrals' },
      { key: 'home_health_referrals', label: 'Home Health Referrals' },
      { key: 'hospice_referrals', label: 'Hospice Referrals' },
      { key: 'snf_referrals', label: 'SNF Referrals' },
      { key: 'dme_referrals', label: 'DME Referrals' },
      { key: 'imaging_referrals', label: 'Imaging Referrals' },
    ],
    groupOptions: [
      { key: 'year', label: 'Year' },
      { key: 'npi', label: 'Provider NPI' },
    ],
    filters: ['year'],
    yearField: 'year',
  },
  ma_inpatient: {
    label: 'MA Inpatient Hospital',
    entity: 'MedicareMAInpatient',
    metrics: [
      { key: 'total_discharges', label: 'Total Discharges' },
      { key: 'total_covered_days', label: 'Covered Days' },
      { key: 'total_stays', label: 'Total Stays' },
      { key: 'persons_served', label: 'Persons Served' },
      { key: 'avg_length_of_stay', label: 'Avg Length of Stay' },
      { key: 'covered_days_per_1000', label: 'Covered Days per 1K' },
      { key: 'discharges_per_1000', label: 'Discharges per 1K' },
      { key: 'total_enrollees', label: 'Total Enrollees' },
    ],
    groupOptions: [
      { key: 'data_year', label: 'Year' },
      { key: 'table_name', label: 'Table' },
      { key: 'hospital_type', label: 'Hospital Type' },
      { key: 'state', label: 'State' },
      { key: 'entitlement_type', label: 'Entitlement Type' },
    ],
    filters: ['year', 'state', 'hospital_type', 'table_name'],
    yearField: 'data_year',
  },
  hha_stats: {
    label: 'Home Health Agency Stats',
    entity: 'MedicareHHAStats',
    metrics: [
      { key: 'persons_served', label: 'Persons Served' },
      { key: 'total_visits', label: 'Total Visits' },
      { key: 'total_episodes', label: 'Total Episodes' },
      { key: 'total_charges', label: 'Total Charges ($)' },
      { key: 'program_payments', label: 'Program Payments ($)' },
      { key: 'payment_per_person', label: 'Payment per Person ($)' },
      { key: 'visits_per_person', label: 'Visits per Person' },
      { key: 'skilled_nursing_visits', label: 'Skilled Nursing Visits' },
      { key: 'pt_visits', label: 'PT Visits' },
    ],
    groupOptions: [
      { key: 'data_year', label: 'Year' },
      { key: 'table_name', label: 'Table' },
      { key: 'state', label: 'State' },
      { key: 'agency_type', label: 'Agency Type' },
    ],
    filters: ['year', 'state', 'table_name'],
    yearField: 'data_year',
  },
  inpatient_drg: {
    label: 'Inpatient DRG',
    entity: 'InpatientDRG',
    metrics: [
      { key: 'total_discharges', label: 'Total Discharges' },
      { key: 'avg_covered_charges', label: 'Avg Covered Charges ($)' },
      { key: 'avg_total_payments', label: 'Avg Total Payments ($)' },
      { key: 'avg_medicare_payments', label: 'Avg Medicare Payments ($)' },
    ],
    groupOptions: [
      { key: 'data_year', label: 'Year' },
      { key: 'state', label: 'State' },
      { key: 'drg_code', label: 'DRG Code' },
    ],
    filters: ['year', 'state'],
    yearField: 'data_year',
  },
  part_d_stats: {
    label: 'Medicare Part D',
    entity: 'MedicarePartDStats',
    metrics: [
      { key: 'total_enrollees', label: 'Total Enrollees' },
      { key: 'total_utilizers', label: 'Total Utilizers' },
      { key: 'avg_annual_fills', label: 'Avg Annual Fills' },
      { key: 'avg_annual_gross_cost', label: 'Avg Annual Gross Cost ($)' },
      { key: 'generic_dispensing_rate', label: 'Generic Dispensing Rate (%)' },
      { key: 'brand_cost', label: 'Brand Cost ($)' },
      { key: 'generic_cost', label: 'Generic Cost ($)' },
      { key: 'total_drug_cost', label: 'Total Drug Cost ($)' },
    ],
    groupOptions: [
      { key: 'data_year', label: 'Year' },
      { key: 'table_name', label: 'Table' },
      { key: 'plan_type', label: 'Plan Type' },
      { key: 'state', label: 'State' },
      { key: 'demographic_group', label: 'Demographic Group' },
    ],
    filters: ['year', 'state', 'table_name'],
    yearField: 'data_year',
  },
  snf_stats: {
    label: 'Medicare SNF',
    entity: 'MedicareSNFStats',
    metrics: [
      { key: 'persons_served', label: 'Persons Served' },
      { key: 'total_stays', label: 'Total Stays' },
      { key: 'total_covered_days', label: 'Covered Days' },
      { key: 'program_payments', label: 'Program Payments ($)' },
      { key: 'beneficiary_payments', label: 'Beneficiary Payments ($)' },
      { key: 'payment_per_stay', label: 'Payment per Stay ($)' },
      { key: 'avg_length_of_stay', label: 'Avg Length of Stay' },
      { key: 'covered_days_per_1000', label: 'Covered Days per 1K' },
      { key: 'stays_per_1000', label: 'Stays per 1K' },
    ],
    groupOptions: [
      { key: 'data_year', label: 'Year' },
      { key: 'table_name', label: 'Table' },
      { key: 'state', label: 'State' },
      { key: 'facility_type', label: 'Facility Type' },
      { key: 'entitlement_type', label: 'Entitlement Type' },
    ],
    filters: ['year', 'state', 'table_name'],
    yearField: 'data_year',
  },
};

export const CHART_COLORS = [
  '#3b82f6', '#ef4444', '#10b981', '#f59e0b', '#8b5cf6',
  '#06b6d4', '#ec4899', '#14b8a6', '#f97316', '#6366f1',
  '#84cc16', '#a855f7',
];